org: yomieth
app: general
service: boilerplate

frameworkVersion: '3'

provider:
  name: aws
  runtime: nodejs16.x
  lambdaHashingVersion: '20201221'
  stage: dev
  environment:
    DUMMY_PARAMETER: "DUMMY_VALUE"

functions:
  api:
    handler: lambda.handler
    events:
      - http:
          path: /
          method: ANY
      - http:
          path: /{proxy+}
          method: ANY


plugins:
  - serverless-offline
  - serverless-plugin-typescript
